# Generated by Django 5.2.4 on 2025-07-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_child"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("student_id", models.CharField(max_length=50, unique=True)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("course", models.CharField(max_length=100)),
            ],
        ),
    ]
